services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque_api
      MYSQL_USER: gregs
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"