// <auto-generated />
using System;
using EstocariaNet.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstocariaNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240713194221_mg_users")]
    partial class mg_users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EstocariaNet.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AplicationUserAdminId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("AdminId");

                    b.HasIndex("AplicationUserAdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = "AdminId",
                            Setor = "Vargas"
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.AplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdminId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EstoquistaId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("EstoquistaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "usuarioEstoquistaRaiz",
                            AccessFailedCount = 0,
                            Email = "estoquista@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            LockoutEnd = new DateTimeOffset(new DateTime(2045, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            NormalizedEmail = "ESTOQUISTA@GMAIL.COM",
                            NormalizedUserName = "ESTOQUISTA",
                            PasswordHash = "",
                            PhoneNumber = "9981998199",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(2045, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoUsuario = 0,
                            TwoFactorEnabled = false,
                            UserName = "Estoquista"
                        },
                        new
                        {
                            Id = "usuarioAdminRaiz",
                            AccessFailedCount = 0,
                            Email = "Admins@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            LockoutEnd = new DateTimeOffset(new DateTime(2045, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "",
                            PhoneNumber = "9981998199",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(2045, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoUsuario = 0,
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nome = "Grãos"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nome = "Em pó"
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoque", b =>
                {
                    b.Property<int>("EstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EstoqueId"));

                    b.Property<float>("Capacidade")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstoqueAdminId")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkAdminAdminId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("EstoqueId");

                    b.HasIndex("LinkAdminAdminId");

                    b.ToTable("Estoques");

                    b.HasData(
                        new
                        {
                            EstoqueId = 1,
                            Capacidade = 1150.5f,
                            DataCriacao = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Local = "Vale dos cangurus",
                            Nome = "EST - Comestíveis SA"
                        },
                        new
                        {
                            EstoqueId = 2,
                            Capacidade = 1650.5f,
                            DataCriacao = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Local = "Vale dos cangurus",
                            Nome = "EST - Prod Limpeza SA"
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoquista", b =>
                {
                    b.Property<string>("EstoquistaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AplicationUserEstoquistaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstoqueId")
                        .HasColumnType("int");

                    b.Property<int?>("EstoquistaEstoqueId")
                        .HasColumnType("int");

                    b.HasKey("EstoquistaId");

                    b.HasIndex("AplicationUserEstoquistaId");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("EstoquistaEstoqueId");

                    b.ToTable("Estoquistas");

                    b.HasData(
                        new
                        {
                            EstoquistaId = "EstoquistaIdRaiz",
                            Celular = "567456546",
                            Cpf = "11800909862",
                            DataInicio = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560)
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Lancamento", b =>
                {
                    b.Property<int>("LancamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LancamentoId"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstoqueaId")
                        .HasColumnType("int");

                    b.Property<string>("EstoquistaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LinkEstoqueEstoqueId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<float>("QuantEntrada")
                        .HasColumnType("float");

                    b.Property<float>("QuantSaida")
                        .HasColumnType("float");

                    b.HasKey("LancamentoId");

                    b.HasIndex("EstoquistaId");

                    b.HasIndex("LinkEstoqueEstoqueId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Lancamentos");

                    b.HasData(
                        new
                        {
                            LancamentoId = 1,
                            Data = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 18f,
                            QuantSaida = 20f
                        },
                        new
                        {
                            LancamentoId = 2,
                            Data = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 5,
                            QuantEntrada = 56f,
                            QuantSaida = 12f
                        },
                        new
                        {
                            LancamentoId = 3,
                            Data = new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 54f,
                            QuantSaida = 4f
                        },
                        new
                        {
                            LancamentoId = 4,
                            Data = new DateTime(2024, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 5,
                            QuantEntrada = 66f,
                            QuantSaida = 3f
                        },
                        new
                        {
                            LancamentoId = 5,
                            Data = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 3,
                            QuantEntrada = 47f,
                            QuantSaida = 3f
                        },
                        new
                        {
                            LancamentoId = 6,
                            Data = new DateTime(2024, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 5,
                            QuantEntrada = 60f,
                            QuantSaida = 1f
                        },
                        new
                        {
                            LancamentoId = 7,
                            Data = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 4,
                            QuantEntrada = 36f,
                            QuantSaida = 20f
                        },
                        new
                        {
                            LancamentoId = 8,
                            Data = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 3,
                            QuantEntrada = 79f,
                            QuantSaida = 28f
                        },
                        new
                        {
                            LancamentoId = 9,
                            Data = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 4,
                            QuantEntrada = 36f,
                            QuantSaida = 24f
                        },
                        new
                        {
                            LancamentoId = 10,
                            Data = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 4,
                            QuantEntrada = 13f,
                            QuantSaida = 9f
                        },
                        new
                        {
                            LancamentoId = 11,
                            Data = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 2,
                            QuantEntrada = 19f,
                            QuantSaida = 5f
                        },
                        new
                        {
                            LancamentoId = 12,
                            Data = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 3,
                            QuantEntrada = 34f,
                            QuantSaida = 4f
                        },
                        new
                        {
                            LancamentoId = 13,
                            Data = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 10f,
                            QuantSaida = 7f
                        },
                        new
                        {
                            LancamentoId = 14,
                            Data = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 5,
                            QuantEntrada = 12f,
                            QuantSaida = 16f
                        },
                        new
                        {
                            LancamentoId = 15,
                            Data = new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 3,
                            QuantEntrada = 59f,
                            QuantSaida = 11f
                        },
                        new
                        {
                            LancamentoId = 16,
                            Data = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 4,
                            QuantEntrada = 21f,
                            QuantSaida = 10f
                        },
                        new
                        {
                            LancamentoId = 17,
                            Data = new DateTime(2024, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 26f,
                            QuantSaida = 20f
                        },
                        new
                        {
                            LancamentoId = 18,
                            Data = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 5,
                            QuantEntrada = 76f,
                            QuantSaida = 9f
                        },
                        new
                        {
                            LancamentoId = 19,
                            Data = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 68f,
                            QuantSaida = 20f
                        },
                        new
                        {
                            LancamentoId = 20,
                            Data = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 3,
                            QuantEntrada = 13f,
                            QuantSaida = 20f
                        },
                        new
                        {
                            LancamentoId = 21,
                            Data = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 19f,
                            QuantSaida = 4f
                        },
                        new
                        {
                            LancamentoId = 22,
                            Data = new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 2,
                            QuantEntrada = 80f,
                            QuantSaida = 22f
                        },
                        new
                        {
                            LancamentoId = 23,
                            Data = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 2,
                            QuantEntrada = 27f,
                            QuantSaida = 18f
                        },
                        new
                        {
                            LancamentoId = 24,
                            Data = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 1,
                            QuantEntrada = 56f,
                            QuantSaida = 28f
                        },
                        new
                        {
                            LancamentoId = 25,
                            Data = new DateTime(2024, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 2,
                            QuantEntrada = 66f,
                            QuantSaida = 25f
                        },
                        new
                        {
                            LancamentoId = 26,
                            Data = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstoquistaId = "EstoquistaIdRaiz",
                            ProdutoId = 2,
                            QuantEntrada = 32f,
                            QuantSaida = 14f
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EstoqueId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Preco")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.Property<float?>("QuantEstoqueMax")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<float?>("QuantEstoqueMin")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<float?>("Saldo")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstoqueId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Descricao = "É o arroz descascado",
                            EstoqueId = 1,
                            ImagemUrl = "algumaimagem.png",
                            Nome = "Arroz Integral",
                            Preco = 6.4m,
                            QuantEstoqueMax = 250f,
                            QuantEstoqueMin = 0f,
                            Saldo = 0f
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Descricao = "Variedade do feijão comum",
                            EstoqueId = 1,
                            ImagemUrl = "algumaimagem.png",
                            Nome = "Feijão carioca",
                            Preco = 6.4m,
                            QuantEstoqueMax = 250f,
                            QuantEstoqueMin = 0f,
                            Saldo = 0f
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Descricao = "Farinha de mandioca",
                            EstoqueId = 1,
                            ImagemUrl = "algumaimagem.png",
                            Nome = "Farinha Granfind",
                            Preco = 6.4m,
                            QuantEstoqueMax = 250f,
                            QuantEstoqueMin = 0f,
                            Saldo = 0f
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Descricao = "Café produzido em Caicó",
                            EstoqueId = 1,
                            ImagemUrl = "algumaimagem.png",
                            Nome = "Café Itans",
                            Preco = 6.4m,
                            QuantEstoqueMax = 250f,
                            QuantEstoqueMin = 0f,
                            Saldo = 0f
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2024, 7, 13, 16, 42, 20, 902, DateTimeKind.Local).AddTicks(1560),
                            Descricao = "Açúcar refinado e cristalino",
                            EstoqueId = 1,
                            ImagemUrl = "algumaimagem.png",
                            Nome = "Açúcar Cristal",
                            Preco = 6.4m,
                            QuantEstoqueMax = 250f,
                            QuantEstoqueMin = 0f,
                            Saldo = 0f
                        });
                });

            modelBuilder.Entity("EstocariaNet.Models.Relatorio", b =>
                {
                    b.Property<int>("RelatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RelatorioId"));

                    b.Property<string>("AdminId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MesAnoPred")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PredProdutoEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("PredProdutoSaida")
                        .HasColumnType("int");

                    b.Property<double?>("PredTotalArrecadar")
                        .HasColumnType("double");

                    b.Property<bool?>("PredicaoProxMeses")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProdutoMaisEntrou")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoMaisSaiu")
                        .HasColumnType("int");

                    b.Property<string>("RelatorioName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<double?>("TotalArrecadado")
                        .HasColumnType("double");

                    b.HasKey("RelatorioId");

                    b.HasIndex("AdminId");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("LancamentoRelatorio", b =>
                {
                    b.Property<int>("LancamentosLancamentoId")
                        .HasColumnType("int");

                    b.Property<int>("RelatoriosRelatorioId")
                        .HasColumnType("int");

                    b.HasKey("LancamentosLancamentoId", "RelatoriosRelatorioId");

                    b.HasIndex("RelatoriosRelatorioId");

                    b.ToTable("LancamentoRelatorio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EstocariaNet.Models.Admin", b =>
                {
                    b.HasOne("EstocariaNet.Models.AplicationUser", "AplicationUser")
                        .WithMany()
                        .HasForeignKey("AplicationUserAdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AplicationUser");
                });

            modelBuilder.Entity("EstocariaNet.Models.AplicationUser", b =>
                {
                    b.HasOne("EstocariaNet.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("EstocariaNet.Models.Estoquista", "Estoquista")
                        .WithMany()
                        .HasForeignKey("EstoquistaId");

                    b.Navigation("Admin");

                    b.Navigation("Estoquista");
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoque", b =>
                {
                    b.HasOne("EstocariaNet.Models.Admin", "LinkAdmin")
                        .WithMany()
                        .HasForeignKey("LinkAdminAdminId");

                    b.Navigation("LinkAdmin");
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoquista", b =>
                {
                    b.HasOne("EstocariaNet.Models.AplicationUser", "AplicationUser")
                        .WithMany()
                        .HasForeignKey("AplicationUserEstoquistaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EstocariaNet.Models.Estoque", null)
                        .WithMany("Estoquistas")
                        .HasForeignKey("EstoqueId");

                    b.HasOne("EstocariaNet.Models.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoquistaEstoqueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AplicationUser");

                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("EstocariaNet.Models.Lancamento", b =>
                {
                    b.HasOne("EstocariaNet.Models.Estoquista", "LinkEstoquista")
                        .WithMany("Lancamentos")
                        .HasForeignKey("EstoquistaId");

                    b.HasOne("EstocariaNet.Models.Estoque", "LinkEstoque")
                        .WithMany("Lancamentos")
                        .HasForeignKey("LinkEstoqueEstoqueId");

                    b.HasOne("EstocariaNet.Models.Produto", "LinkProduto")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("LinkEstoque");

                    b.Navigation("LinkEstoquista");

                    b.Navigation("LinkProduto");
                });

            modelBuilder.Entity("EstocariaNet.Models.Produto", b =>
                {
                    b.HasOne("EstocariaNet.Models.Categoria", "LinkCategoria")
                        .WithMany("ProdutoLink")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("EstocariaNet.Models.Estoque", "LinkEstoque")
                        .WithMany("Produtos")
                        .HasForeignKey("EstoqueId");

                    b.Navigation("LinkCategoria");

                    b.Navigation("LinkEstoque");
                });

            modelBuilder.Entity("EstocariaNet.Models.Relatorio", b =>
                {
                    b.HasOne("EstocariaNet.Models.Admin", "LinkAdmin")
                        .WithMany("Relatorios")
                        .HasForeignKey("AdminId");

                    b.Navigation("LinkAdmin");
                });

            modelBuilder.Entity("LancamentoRelatorio", b =>
                {
                    b.HasOne("EstocariaNet.Models.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentosLancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstocariaNet.Models.Relatorio", null)
                        .WithMany()
                        .HasForeignKey("RelatoriosRelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EstocariaNet.Models.AplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EstocariaNet.Models.AplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstocariaNet.Models.AplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EstocariaNet.Models.AplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstocariaNet.Models.Admin", b =>
                {
                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("EstocariaNet.Models.Categoria", b =>
                {
                    b.Navigation("ProdutoLink");
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoque", b =>
                {
                    b.Navigation("Estoquistas");

                    b.Navigation("Lancamentos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("EstocariaNet.Models.Estoquista", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("EstocariaNet.Models.Produto", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
